# docker-compose.yml file
version: '3'

services:

  nginx:
    build: ./
    container_name: web_nginx
    restart: unless-stopped
    environment:
      TZ: "Europe/Minsk"
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./bakery-website-template/:/app/static/
